# Generated by Django 5.2 on 2025-04-24 00:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Curtida',
                'verbose_name_plural': 'Curtidas',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('imagem_capa', models.URLField(blank=True, max_length=500)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('fonte', models.CharField(choices=[('youtube', 'YouTube'), ('youtube_music', 'YouTube Music'), ('spotify', 'Spotify')], max_length=20)),
                ('url_original', models.URLField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('situacao', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('artista', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('duracao', models.IntegerField(help_text='Duração em segundos')),
                ('url', models.URLField(max_length=500)),
                ('ordem', models.IntegerField()),
                ('imagem_capa', models.URLField(blank=True, max_length=500)),
                ('data_adicionada', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_edicao', models.DateTimeField(blank=True, null=True)),
                ('comentario_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='playlists.comment')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
